CREATE DATABASE postgis_raster;

CREATE EXTENSION postgis;
CREATE EXTENSION postgis_raster;

CREATE SCHEMA IF NOT EXISTS weronika_jopek;
CREATE SCHEMA IF NOT EXISTS public;
CREATE SCHEMA IF NOT EXISTS rasters;
CREATE SCHEMA IF NOT EXISTS vectors;

